//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LennyBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public string[] owned {
            get {
                return ((string[])(this["owned"]));
            }
            set {
                this["owned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public string[] users {
            get {
                return ((string[])(this["users"]));
            }
            set {
                this["users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfInt xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
  <int>0</int>
</ArrayOfInt>")]
        public int[] coins {
            get {
                return ((int[])(this["coins"]));
            }
            set {
                this["coins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfBoolean xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>fals" +
            "e</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>" +
            "false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <bool" +
            "ean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>fals" +
            "e</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>" +
            "false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <bool" +
            "ean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <" +
            "boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r" +
            "\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boole" +
            "an>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</b" +
            "oolean>\r\n  <boolean>false</boolean>\r\n  <boolean>false</boolean>\r\n</ArrayOfBoolea" +
            "n>")]
        public bool[] inLottery {
            get {
                return ((bool[])(this["inLottery"]));
            }
            set {
                this["inLottery"] = value;
            }
        }
    }
}
